spring:
  application:
    name: family

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/family
    username: root
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

server:
  port: 8080

