package com.pthinh.family.Enum;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum Role {
    ADMIN_SYSTEM("ADMIN_SYSTEM"),
    USER("USER"),
    AUNT_FATHER("AUNT_FATHER"),
    AUNT_MOTHER("AUNT_MOTHER"),
    AVUNCULAR_FATHER("AVUNCULAR_FATHER"),
    AVUNCULAR_MOTHER("AVUNCULAR_MOTHER"),
    BROTHER("BROTHER"),
    SISTER("SISTER"),
    FATHER("FATHER"),
    MOTHER("MOTHER"),
    GRANDMOTHER_FATHER("GRANDMOTHER_FATHER"),
    GRANDMOTHER_MOTHER("GRANDMOTHER_MOTHER"),
    GRANDFATHER_FATHER("GRANDFATHER_FATHER"),
    GRANDFATHER_MOTHER("GRANDFATHER_MOTHER"),
    GRANDCHILDREN_FATHER("GRANDCHILDREN_FATHER"),
    GRANDCHILDREN_MOTHER("GRANDCHILDREN_MOTHER");

    private final String role;
}
